name: ssh command
on:
  push:
    branches:
      - main #どのブランチにpushされたらjobを起動するか

jobs:
  deploy1:  #jobは複数定義できる
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Development #nameはなくても良い
        id: dev_ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.dev_ssh.outputs.SERVER }} bash /app/deploy.sh takumi_kazakoshi

  deploy2:
    needs: deploy1 #ジョブは本来並行して実行されるがneedsキーワードで指定したジョブが完了するのを待てる
    runs-on: ubuntu-latest
    if: success() #ifに対してsuccess()を定義することで前のジョブが成功した場合にのみ実行する条件にできる（ifの条件は他にもいろいろ定義可）
    steps:
      - name: SSH to Production
        id: prod_ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSHE_SSH_KEY }}
      - run: ssh ${{ steps.prod_ssh.outputs.SERVER }} bash /app/deploy.sh takumi_kazakoshi #-vをつけることで詳細なデバッグが出力
