name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: invi5H/ssh-action@v1
      with:
        SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
        SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
        SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}

    - name: Run Tests on Staging
      run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy_test.sh takumi_kazakoshi

    - name: Deploy to Production
      if: success()
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.PROD_SSH_PORT }} ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} 'bash /app/deploy_production.sh'
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

env:
  STAGING_SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
  STAGING_SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
  STAGING_SSH_USER: ${{ secrets.STAGING_SSH_USER }}
  STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
  PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
  PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
  PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
  PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
